language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2/repository/io
    - $HOME/.m2/repository/it
    - $HOME/.m2/repository/org
    - $HOME/.m2/repository/mysql

sudo: false

before_install:
  - rm -f ~/.m2/settings.xml
