sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
script:
  - mvn -B -fae -Dall clean install
notifications:
  email: false
  on_failure: never
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
jdk: 
  - oraclejdk8
addons:
  apt:
    packages:
      - python-sphinx
