before_install:
#  - "git clone -b travis `git config --get remote.origin.url` target/travis"
#  - chmod 777 ./scripts/*.sh
# script: ./scripts/build.sh
# after_script: ./scripts/javadoc.sh
language: java
# notifications:
#   email: false
#   hipchat:
#     rooms:
#       secure: Yw7l3qr8ymHAXAFujkjbC8TKBYxMXZF9eWSgbAr4kJLMCL6GXcWYbVL6gcYcPXgBJyeUzcAoy+XSmU+F+jUv5aNN19171kKaJaTyFi8OAxjxSqyqwnlqhmYMzo7gMKnOiuLzQVuE8OBd3kizBKyvMFsrhTjA+iYYc5fPG20XrY8=
install: true
sudo: false
matrix:
  include:
  - jdk: oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
# env:
#   global:
#     - secure: "ewpnnG41+tNBDWHcU69RlQlqItVHQcCso+Dc+gEJdEUSXTHowj18lQR7DpOIsZmnOrg9yP35dXQnoTgnsduvBCZWoUToqoHyiIXBswBmv+s3zwoJ1gBl6l4Wt7uVEW+W8+eCJxxU1NXs43KcCyjx/vL6PHOaDSGBuZYLRdF/3fM="
#     - secure: "M8cFHpjB09qIebLFosrU7udDyiLas9iEQ+Wr74Ao5sqZQ9lOdmqco3bV96W/eblDU3KqMpCXHdgmDhpzgAHZQMEpxDZqu6ifpeNu6uuET4tX5NEj2xudbLf3CUCSc7GSzhxen3Oz1aP9MxNmjS6aXSgddZmmeG/LIGx7g3YQW+Y="
#     - secure: "XlEsd+3wdxkYXGGrWQrNEeiwXnaEqQaQ2LhyN2SKuml2PU0LqZk7aH4hJArB4bOPbEtyGndm8OOoXhgfbatpDXsRG+BLRK+soTqew2M4oUBLIQaNBIgKYdXuMFb986GODOlV6ECgeX4EfToL4g4HuOCRmLBV/cFndWhAlgKbJbE="
#     - secure: "H8HTOwCBB2Aq02zgC4VfF8rcLjLciGiAfjlEylH6M5hnNuO9E842d+1Pu4K5DhwME3olyF0WFDXrTPkZulQBbYYXhVA7eiqCznACORiRYokYQ8eTsiYTQsHgexK8o1pugrOqNyiQJu0MnHMXQxCyYM8xDHEL5NwKMERqweivOr8="
after_success:
#   - mvn cobertura:cobertura coveralls:report
  - "git clone -b travis `git config --get remote.origin.url` travis"
  - mvn clean install test deploy jacoco:report coveralls:report cobertura:cobertura --settings ./travis/settings.xml
  - ls -lah target/
  - bash <(curl -s https://codecov.io/bash)
