---
- name: Set ovirt_vds_vds_id fact
  set_fact:
    ovirt_vds_vds_id: unknown_id_{{ ansible_machine_id }}
  when: not ovirt_vds_vds_id is defined

- name: Configure oVirt processing
  template:
    src: ovirt-processing.conf
    dest: '{{ fluentd_config_parts_dir }}/20-ovirt-processing.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: restart fluentd
